version: '3'

services:
  server:
    build:
      context: .
      dockerfile: .deploy/Dockerfile.server
    image: server:latest
    container_name: server-pow
    restart: always

  client:
    build:
      context: .
      dockerfile: .deploy/Dockerfile.client
    image: client:latest
    container_name: client-pow
    environment:
      - SERVER_ADDR=server:8000
    depends_on:
      - server
    links:
      - server